
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author jofie
 */
public class ListaSuperMercado extends javax.swing.JFrame {

    /**
     * Creates new form ListaSuperMercado
     */
    public ListaSuperMercado() {
        initComponents();
        llenarLista();
    }
    DefaultListModel listaMandado = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campoMandado = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        campoProducto = new javax.swing.JTextField();
        agregarProducto = new javax.swing.JButton();
        bBucarMejoresPrecios = new javax.swing.JButton();
        bBorrarLista = new javax.swing.JButton();
        bBorrarProducto = new javax.swing.JButton();
        bCasa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(campoMandado);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setText("Lista Para El Super Mercado");

        campoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoProductoKeyPressed(evt);
            }
        });

        agregarProducto.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        agregarProducto.setText("Agregar");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        bBucarMejoresPrecios.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        bBucarMejoresPrecios.setText("Buscar Los Mejores Precios");
        bBucarMejoresPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBucarMejoresPreciosActionPerformed(evt);
            }
        });

        bBorrarLista.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bBorrarLista.setText("Borrar Lista");
        bBorrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarListaActionPerformed(evt);
            }
        });

        bBorrarProducto.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bBorrarProducto.setText("Borrar Producto");
        bBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarProductoActionPerformed(evt);
            }
        });

        bCasa.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bCasa.setText("Casa");
        bCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBucarMejoresPrecios)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bBorrarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bBorrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(agregarProducto)
                                .addComponent(campoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCasa)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bCasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarProducto)
                        .addGap(35, 35, 35)
                        .addComponent(bBorrarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(bBorrarLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(bBucarMejoresPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Aqui se agregan los productos a la lista
     * mediante un boton
     * @param evt 
     */
    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        String tPalabra = campoProducto.getText();
        if (tPalabra.equals("")) {
        } else {
            int tamaño = campoMandado.getLastVisibleIndex();
            if (tamaño < 0) {
                campoMandado.setModel(listaMandado);
                listaMandado.addElement(campoProducto.getText());
                campoProducto.setText("");
            } else {
                for (int i = 0; i <= tamaño; i++) {
                    if (tPalabra.equals((String) listaMandado.getElementAt(i))) {
                        JOptionPane.showMessageDialog(null, "Ya tienes estre producto en tu lista");
                        break;
                    } else if (i == tamaño) {
                        campoMandado.setModel(listaMandado);
                        listaMandado.addElement(campoProducto.getText());
                        campoProducto.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_agregarProductoActionPerformed
    /**
     * Es para boorar de la lista 
     * el producto que el usuario selecciono
     * @param evt 
     */
    private void bBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarProductoActionPerformed
        int index = campoMandado.getSelectedIndex();
        if (index >= 0) {
            listaMandado.remove(index);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el producto que desea quitar de la lista");
        }
    }//GEN-LAST:event_bBorrarProductoActionPerformed
    /**
     * Se elimina toda la lista
     * @param evt 
     */
    private void bBorrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarListaActionPerformed
        listaMandado.removeAllElements();
        campoMandado.setModel(listaMandado);
    }//GEN-LAST:event_bBorrarListaActionPerformed
    /**
     * Se agrega un producto a la lista
     * usando la tecla enter
     * @param evt 
     */
    private void campoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoProductoKeyPressed
        if (evt.getKeyCode() == 10) {
            String tPalabra = campoProducto.getText();
            if (tPalabra.equals("")) {
            } else {
                int tamaño = campoMandado.getLastVisibleIndex();
                if (tamaño < 0) {
                    campoMandado.setModel(listaMandado);
                    listaMandado.addElement(campoProducto.getText());
                    campoProducto.setText("");
                } else {
                    for (int i = 0; i <= tamaño; i++) {
                        if (tPalabra.equals((String) listaMandado.getElementAt(i))) {
                            JOptionPane.showMessageDialog(null, "Ya tienes estre producto en tu lista");
                            break;
                        } else if (i == tamaño) {
                            campoMandado.setModel(listaMandado);
                            listaMandado.addElement(campoProducto.getText());
                            campoProducto.setText("");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_campoProductoKeyPressed
    /**
     * Se regresa a la ventana principal
     * del usuario y se llena la lista de
     * productos del usuario dependiendo de
     * los producto que haya agregado hasta este
     * punto
     * @param evt 
     */
    private void bCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCasaActionPerformed
        llenarConProductosActuales();
        dispose();
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
    }//GEN-LAST:event_bCasaActionPerformed
    /**
     * Se llena la lista con todos los producto que
     * eligio el usuario y se pasa a la siguiente 
     * ventana
     * @param evt 
     */
    private void bBucarMejoresPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBucarMejoresPreciosActionPerformed
        //Crear lista con los productos
        if (campoMandado.getLastVisibleIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Tu lista esta vacia");
        } else {
            llenarConProductosActuales();
            dispose();
            ListasMercado ventana = new ListasMercado();
            ventana.setVisible(true);
        }
        /*
        String mensaje = "";
        for (int i = 0; i < tListaProductos.contarNodos(); i++) {
            Producto tProducot = (Producto)Mercadito.listaProductosUsuario.get(i).getiVal();
            mensaje = mensaje + tProducot.getNombre()+"\n";
        }
        JOptionPane.showMessageDialog(null, mensaje);*/
    }//GEN-LAST:event_bBucarMejoresPreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSuperMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSuperMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSuperMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSuperMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaSuperMercado().setVisible(true);
            }
        });
    }
    /**
     * Este metodo sirve para llenar la lista de productos
     * del usuario con lo datos que metio en la lista que se
     * le muestra
     */
    public void llenarLista() {
        ListaDE tListaProductos = Mercadito.listaProductosUsuario;
        for (int i = 0; i < tListaProductos.contarNodos(); i++) {
            Producto tProducot = (Producto) tListaProductos.get(i).getiVal();
            campoMandado.setModel(listaMandado);
            listaMandado.addElement(tProducot.getNombre());
        }
    }
    /**
     * Este metodo es para guardar en la computadora
     * la lista de productos y anexarla con el usuario
     */
    public void llenarConProductosActuales() {
        int tamaño = campoMandado.getLastVisibleIndex();
        ListaDE tListaProductos = new ListaDE();
        for (int i = 0; i <= tamaño; i++) {
            Producto tProducto = new Producto((String) listaMandado.getElementAt(i));
            Nodo<Producto> tNodo = new Nodo(tProducto);
            tListaProductos.agregarNodo(tNodo);
        }
        Mercadito.listaProductosUsuario = tListaProductos;
        User tUser = (User)(Mercadito.listaUsuarios.get(Mercadito.posicionUsuario).getiVal());
        tUser.setListaProductos(Mercadito.listaProductosUsuario);
        try {
            FileOutputStream archivoSalidaUno = new FileOutputStream(Mercadito.nombreListaU);
            ObjectOutputStream salidaDeDato = new ObjectOutputStream(archivoSalidaUno);
            salidaDeDato.writeObject(Mercadito.listaUsuarios);
            salidaDeDato.close();
        } catch (IOException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProducto;
    private javax.swing.JButton bBorrarLista;
    private javax.swing.JButton bBorrarProducto;
    private javax.swing.JButton bBucarMejoresPrecios;
    private javax.swing.JButton bCasa;
    private javax.swing.JList<String> campoMandado;
    private javax.swing.JTextField campoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
