
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author jofie
 */
public class usuario extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     * Se adquiere la lista con todos los usuarios
     * que se han creado
     */
    public usuario() {
        initComponents();
        try {
            FileInputStream leector = new FileInputStream(Mercadito.nombreListaU);
            ObjectInputStream datoEntrada = new ObjectInputStream(leector);
            Mercadito.listaUsuarios = (ListaDE) datoEntrada.readObject();
            datoEntrada.close();
        } catch (IOException | ClassNotFoundException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        bCrearUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoClaveUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setText("Mercadito");

        bIngresar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bCrearUsuario.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bCrearUsuario.setText("Crear Usuario");
        bCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setText("Usuario/Nombre");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        campoClaveUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoClaveUsuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(campoClaveUsuario))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bIngresar)
                        .addGap(18, 18, 18)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCrearUsuario)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Manda a la ventana de crear usuario
     * @param evt 
     */
    private void bCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearUsuarioActionPerformed
        dispose();
        CrearUsuario ventana = new CrearUsuario();
        ventana.setVisible(true);
    }//GEN-LAST:event_bCrearUsuarioActionPerformed
    /**
     * Compara los datos que se ingresan con los de la 
     * lista de usuarios para comprobar si exite el usuario
     * y si son correctos los datos
     * @param evt 
     */
    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        String tUsuario = campoNombreUsuario.getText();
        String tContraseña = campoClaveUsuario.getText();
        ListaDE tListaUsuarios = Mercadito.listaUsuarios;
        for (int i = 0; i < tListaUsuarios.contarNodos(); i++) {
            User tUser = (User) tListaUsuarios.get(i).getiVal();
            if (tUser.getNombre().equals(tUsuario) && tUser.getContraseña().equals(tContraseña)) {
                Mercadito.posicionUsuario = i;
                Mercadito.mensajeMandadoUsuario = tUser.getUltimaListaP();
                Mercadito.listaProductosUsuario = tUser.getListaProductos();
                Mercadito.nombreUsuario = tUser.getNombre();
                dispose();
                VentanaPrincipal ventana = new VentanaPrincipal();
                ventana.setVisible(true);
            } else if (i == tListaUsuarios.contarNodos() - 1) {
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos");
            }
        }
        if (tListaUsuarios.contarNodos() == 0) {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos");
        }
    }//GEN-LAST:event_bIngresarActionPerformed
    /**
     * Compara los datos que se ingresan con los de la 
     * lista de usuarios para comprobar si exite el usuario
     * y si son correctos los datos
     * Mediante la tecla enter
     * @param evt 
     */
    private void campoClaveUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoClaveUsuarioKeyPressed
        if (evt.getKeyCode() == 10) {
            String tUsuario = campoNombreUsuario.getText();
            String tContraseña = campoClaveUsuario.getText();
            ListaDE tListaUsuarios = Mercadito.listaUsuarios;
            for (int i = 0; i < tListaUsuarios.contarNodos(); i++) {
                User tUser = (User) tListaUsuarios.get(i).getiVal();
                if (tUser.getNombre().equals(tUsuario) && tUser.getContraseña().equals(tContraseña)) {
                    Mercadito.posicionUsuario = i;
                    Mercadito.mensajeMandadoUsuario = tUser.getUltimaListaP();
                    Mercadito.nombreUsuario = tUser.getNombre();
                    dispose();
                    VentanaPrincipal ventana = new VentanaPrincipal();
                    ventana.setVisible(true);
                } else if (i == tListaUsuarios.contarNodos() - 1) {
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos");
                }
            }
            if (tListaUsuarios.contarNodos() == 0) {
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos");
            }
        }
    }//GEN-LAST:event_campoClaveUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearUsuario;
    private javax.swing.JButton bIngresar;
    private javax.swing.JPasswordField campoClaveUsuario;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
