
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jofie
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     * Se muestra la ultima lista de mandado que hizo el usuario 
     * en caso de que tenga una
     */
    public VentanaPrincipal() {
        initComponents();
        mensajeBienvenida.setText("Casa De " + Mercadito.nombreUsuario);
        campoListaMandado.setText(Mercadito.mensajeMandadoUsuario);
        try {
            FileInputStream leector = new FileInputStream(Mercadito.NOMBRELISTACOMENTARIOS);
            ObjectInputStream datoEntrada = new ObjectInputStream(leector);
            Mercadito.listaComentarios = (ListaDE) datoEntrada.readObject();
            datoEntrada.close();
        } catch (IOException | ClassNotFoundException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        mensajeBienvenida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoListaMandado = new javax.swing.JTextArea();
        bCrearNuevaListaMandado = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bComunidad = new javax.swing.JButton();
        bSuperOfertas = new javax.swing.JButton();
        bSalida = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensajeBienvenida.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        mensajeBienvenida.setText("Casa De Usuario");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Ultima Lista Del Mandado");

        campoListaMandado.setEditable(false);
        campoListaMandado.setColumns(20);
        campoListaMandado.setRows(5);
        jScrollPane2.setViewportView(campoListaMandado);

        bCrearNuevaListaMandado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bCrearNuevaListaMandado.setText("Crear Nueva Lista");
        bCrearNuevaListaMandado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearNuevaListaMandadoActionPerformed(evt);
            }
        });

        bComunidad.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bComunidad.setText("Comunidad");
        bComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComunidadActionPerformed(evt);
            }
        });

        bSuperOfertas.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bSuperOfertas.setText("Super Ofertas");
        bSuperOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuperOfertasActionPerformed(evt);
            }
        });

        bSalida.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bSalida.setText("Cerrar Sesion");
        bSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCrearNuevaListaMandado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSalida))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 132, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bSuperOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bComunidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(mensajeBienvenida)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(mensajeBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bComunidad)
                        .addGap(36, 36, 36)
                        .addComponent(bSuperOfertas))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(bSalida)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bCrearNuevaListaMandado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Se cierra la secion del usuario
     * @param evt 
     */
    private void bSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalidaActionPerformed
        Mercadito.listaProductosUsuario = new ListaDE();
        dispose();
        usuario ventana = new usuario();
        ventana.setVisible(true);
    }//GEN-LAST:event_bSalidaActionPerformed
    /**
     * Lo manda a la ventana para crear  una lista 
     * nueva para el mandado
     * @param evt 
     */
    private void bCrearNuevaListaMandadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearNuevaListaMandadoActionPerformed
        dispose();
        ListaSuperMercado ventana = new ListaSuperMercado();
        ventana.setVisible(true);
    }//GEN-LAST:event_bCrearNuevaListaMandadoActionPerformed
    /**
     * Manda a la ventana de la comuniad
     * @param evt 
     */
    private void bComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComunidadActionPerformed
        dispose();
        Comunidad ventana = new Comunidad();
        ventana.setVisible(true);
    }//GEN-LAST:event_bComunidadActionPerformed
    /**
     * Manda a la ventana de super ofertas
     * @param evt 
     */
    private void bSuperOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuperOfertasActionPerformed
        dispose();
        SuperOfertas ventana = new SuperOfertas();
        ventana.setVisible(true);
    }//GEN-LAST:event_bSuperOfertasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComunidad;
    private javax.swing.JButton bCrearNuevaListaMandado;
    private javax.swing.JButton bSalida;
    private javax.swing.JButton bSuperOfertas;
    private javax.swing.JTextArea campoListaMandado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensajeBienvenida;
    // End of variables declaration//GEN-END:variables
}
